### ISSUE TITLE
ibvirt_exporter 수집 데이터 토폴로지로 표현 방법 연구 (skydive + grafana)

### ISSUE THREAD

**Issue by qoxown12** [ablecloud-team/ablestack-monitor#11]
#### 이슈 타입

~~~
 * 새 기능 아이디어
 ~~~

#### 컴포넌트 이름

~~~
libvirt_exporter, skydive, grafana
~~~

#### ABLESTACK 버전

~~~
ABLESTACK Bronto
~~~

#### 구성

~~~
topology
~~~

#### OS / 환경

~~~
CentOS 8.3, libvirt_exporter, skydive, grafana
~~~

#### 이슈 내용

libvirt_exporter로 수집한 클러스터의 정보를 토폴로지로 표현할 수 있는 방법 연구

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by stardom3645** [comment]
## SkyDive

### 설치 순서 및 방법

#### 설치 환경
- centos 8.3.2011
- grafana 7.x
- elastic search

#### SkyDive 설치
1. 최신 바이너리를 다운받고 Allinone 모드(Agent와 Analyzer를 함께 실행)로 실행합니다. 
``
curl -Lo - https://github.com/skydive-project/skydive-binaries/raw/jenkins-builds/skydive-latest.gz | gzip -d > skydive && chmod +x skydive && sudo mv skydive /usr/local/bin/
``
2. 그라파나에 Skydive 데이터 소스를 추가하기 위해서는 storage backend가 필요하며 Skydive는 Elasticsearch와 OrientDB 두 종류를 지원합니다.
 그리고 Skydive의 실행명령어와 함께 옵션으로 설정파일 수정한 후 지정하여 실행합니다.
  - skydive.yml 내용

    ``
    agent:
      topology:
        probes:
          - ovsdb
          - docker
          - runc

    runc:
      run_path:
      - /var/run/runc
      - /var/run/runc-ctrs
  
  analyzer:
    listen: 0.0.0.0:8082
  
    flow:
     backend: myelasticsearch
  
    topology:
     backend: myelasticsearch
  
  
  storage:
      myelasticsearch:
        driver: elasticsearch
        host: 127.0.0.1:9200
  
  ``


``
skydive allinone --conf /etc/skydive.yml
``

**Comment by stardom3645** [comment]
호스트 (ablecube)에서 skydive 실행 시
``
2021-05-18T15:00:39.446+0900	ERROR	netlink/sriov.go:138 (*Probe).handleSriov	ablecube2: SR-IOV: cannot get numvfs of PCI - All attempts fail:
``

에러가 발생합니다.

**Comment by stardom3645** [comment]
## Skydive 그라파나 연동

1. 그라파나에 Skydive 데이터 소스를 추가하기 위해서는 storage backend가 필요하며 Skydive는 Elasticsearch와 OrientDB 두 종류를 지원합니다. 아래의 예에서는 Elasticsearch를 사용합니다.
 그리고 Skydive 실행 시 옵션으로 설정파일을 수정한 후 실행합니다.

    ```
    $ vi /etc/skydive.yml

    agent:
      topology:
        probes:
          - ovsdb
          - docker
          - runc
    
      runc:
        run_path:
        - /var/run/runc
        - /var/run/runc-ctrs
    
    analyzer:
      listen: 0.0.0.0:8082
    
      flow:
       backend: myelasticsearch
    
      topology:
       backend: myelasticsearch
    
    
    storage:
        myelasticsearch:
          driver: elasticsearch
          host: 127.0.0.1:9200
    ```

3. Skydive 설치 확인
http://localhost:8082 를 접속하여 Web UI에서 정상 작동되는지 확인합니다.


4. Skydive 데이터소스를 추가합니다.


#### 그라파나에 Skydive 데이터 소스 추가

```
$ cd /var/lib/grafana/plugins/ 
* 그라파나 설치 방법에 따라 상기 플러그인 폴더와 다른 경로가 사용될 수 있습니다.(etc/grafana/provisioning/datasources/)
$ wget https://grafana.com/api/plugins/skydive-datasource/versions/1.2.0/download
```
또는

```
grafana-cli plugins install skydive-datasource
```

**Comment by kt-cheon** [comment]
skydive는 grafana와 별도의 웹 페이지를 통해서 제공됩니다.

**Comment by stardom3645** [comment]
skydive의 이슈 등록 및 개발은 

[skydive](https://github.com/ablecloud-team/skydive.git "skydive")
[skydive-ui](https://github.com/ablecloud-team/skydive-ui.git "skydive-ui")
에서 진행됩니다.
