### ISSUE TITLE
node, windows exporter 사용자가 가상머신에 직접 설치 하여 설치 할 방안

### ISSUE THREAD

**Issue by qoxown12** [ablecloud-team/ablestack-monitor#12]
#### 이슈 타입

~~~
 * 새 기능 아이디어
 ~~~

#### 컴포넌트 이름

~~~
node_exporter, windows_exporter
~~~

#### ABLESTACK 버전

~~~
ABLESTACK Bronto
~~~

#### 구성

~~~
topology
~~~

#### OS / 환경

~~~
CentOS 8.3, node_exporter, windows_exporter
~~~

#### 이슈 내용

사용자가 특정 가상머신에 exporter를 설치하여 데이터를 수집할 경우 exporter 프로그램의 설치 및 설정을 편리하게 하기 위한 방법 연구 필요

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by kt-cheon** [comment]
Bronto 버전에서는 사용자 가상머신에 별도의 에이전트를 설치하여 모니터링을 제공하지 않습니다.
차기 버전에서 제공될 예정입니다.
