### ISSUE TITLE
grafana cmd 기능연구 확인

### ISSUE THREAD

**Issue by qoxown12** [ablecloud-team/ablestack-monitor#14]
#### 이슈 타입

~~~
 * 기타
 ~~~

#### 컴포넌트 이름

~~~
grafana
~~~

#### ABLESTACK 버전

~~~
ABLESTACK Bronto
~~~

#### 구성

~~~
cmd
~~~

#### OS / 환경

~~~
CentOS 8.3, grafana
~~~

#### 이슈 내용

grafana 통해 모니터링 중인 가상머신에 대한 cmd를 통해 가상머신을 제어하는 방법에 대한 연구

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by kt-cheon** [comment]
grafana cmd를 이용하여 plugin 등을 설치할 수 있으나 가상머신에 대한 제어는 어렵습니다.
