### ISSUE TITLE
grafana 브랜딩 작업 및 한글화

### ISSUE THREAD

**Issue by qoxown12** [ablecloud-team/ablestack-monitor#16]
#### 이슈 타입

~~~
 * 새 기능 아이디어
 ~~~

#### 컴포넌트 이름

~~~
grafana
~~~

#### ABLESTACK 버전

~~~
ABLESTACK Bronto
~~~

#### 구성

~~~
Branding, 한글화
~~~

#### OS / 환경

~~~
CentOS 8.3, grafana
~~~

#### 이슈 내용

grafana branding 작업 및 한글화 방안에 대한 연구

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by kt-cheon** [comment]
Grafana는 Wall 로 브랜딩 및 한글화 되어 Bronto 버전에서 제공됩니다.

**Comment by leca777** [comment]
https://github.com/ablecloud-team/ablestack-wall/pull/5
