### ISSUE TITLE
가상머신에 직접 exporter를 설치하여 사용 시나리오 연구

### ISSUE THREAD

**Issue by qoxown12** [ablecloud-team/ablestack-monitor#17]
#### 이슈 타입

~~~
 * 기타
 ~~~

#### 컴포넌트 이름

~~~
node_exporter, windows_exporter
~~~

#### ABLESTACK 버전

~~~
ABLESTACK Bronto
~~~

#### 구성

~~~
시나리오
~~~

#### OS / 환경

~~~
CentOS 8.3, prometheus, node_exporter, windows_exporter
~~~

#### 이슈 내용

가상머신에 익스포터를 설치하여 모니터링을 진행할 경우에 대한 시나리오 작성

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by kt-cheon** [comment]
사용자가 자신의 가상머신에 exporter를 설치하여 모니터링 하는 기능은 Bronto 버전에서 제공하지 않습니다.
차기 버전에서 개발 예정입니다.
