### ISSUE TITLE
grafana의 데이터소스를 mysql(cloudstack)과 prometheus를 조합하여 모니터링

### ISSUE THREAD

**Issue by qoxown12** [ablecloud-team/ablestack-monitor#18]
#### 이슈 타입

~~~
 * 새 기능 아이디어
 ~~~

#### 컴포넌트 이름

~~~
grafana, mysql, prometheus
~~~

#### ABLESTACK 버전

~~~
ABLESTACK Bronto
~~~

#### 구성

~~~
모니터링
~~~

#### OS / 환경

~~~
CentOS 8.3, grafana, mysql, prometheus
~~~

#### 이슈 내용

ABLESTACK monitoring은 grafana를 활용하여 시각화를 구현하고 데이터 소스는 mysql과 prometheus를 사용합니다.
prometheus로 데이터를 수집할 경우 Mold의 mysql 데이터와 조합하여 모니터링 화면을 구성해야 합니다.
exporter로 수집한 모니터링 데이터와 mysql을 조합하여 데시보드 구성해야합니다.

예를들어 libvirt_exporter로 수집하는 데이터는 아래와 같습니다.
```
libvirt_domain_memory_stats_used_percent{domain="i-19-185-VM", instance="10.10.1.1:9177", job="libvirt"}
```

메모리 사용량 퍼센트의 값을 구분할 수 있는 키 값이 domain, instance, job 정보 밖에 존재하지 않습니다.
가상머신 i-12-219-VM이 Mold에서 사용하는 가상머신의 이름인 tj-vm과 매칭이 필요 합니다.

또

아래와 같이 가상머신 i-19-185-VM의 디스크 쓰기 총량 정보에서
```
libvirt_domain_block_stats_write_bytes_total{domain="i-19-185-VM", instance="10.10.1.1:9177", job="libvirt", source_file="rbd/41446f7b-6124-4de3-83df-5f1da66e4edf", target_device="vda"}
libvirt_domain_block_stats_write_bytes_total{domain="i-19-185-VM", instance="10.10.1.1:9177", job="libvirt", source_file="rbd/144170bf-a46f-4803-b20f-159dc1abdbd8", target_device="vdb"}
```
i-19-185-VM 가상머신에 디스크가 2개 존재하는데 Mold에서 사용하는 볼륨 명인 "ROOT-175"와 "tj-volume"을 매칭할 수 있는지 확인 필요

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by qoxown12** [comment]
1. variables를 활용하는 방법
exporter로 수집하는 가상머신의 도메인 정보와 Mold의 Mysql 테이블 정보를 조합하여 가상머신 그룹화

|Variable|설명|
|-|---|
|user|Mold에서 사용중인 사용자 목록 출력|
|vm_name|선택한 user가 소유하고 있는 가상머신 명 목록 출력|

![2021-05-20 오전 11 00 27](https://user-images.githubusercontent.com/39186243/118907736-09a67b00-b95b-11eb-88e4-b36059a9e6c7.png)
ㅁ

variables에 Mysql의 user와 vm_instance 테이블의 데이터를 조합하여 특정 사용자가 가지고 있는 가상머신을 특정할 수 있다.

**Comment by qoxown12** [comment]
연구결과 해당이슈는 Mold Mysql과 libvirt_exporter로 수집한 prometheus 데이터를 join할 방법이 없습니다.

다른 방법으로 libvirt_exporter를 커스터마이징 하여 Mold에서 필요한 데이터를 libvirt_exporter로 metric 데이터를 prometheus 수집할 때  label에 등록할 수 있도록 기능을 개선하여 사용해야함

해당 관련 이슈는 을 참조

**Comment by kt-cheon** [comment]
libvirt_exporter에서 데이터를 수집할 때 label에 등록될 수 있도록 개발 완료 되었습니다.
