### ISSUE TITLE
libvirt_exporter 메모리 사용량 데이터 확인을 위한 가상머신 OS 별 memballoon 드라이버 설정

### ISSUE THREAD

**Issue by qoxown12** [ablecloud-team/ablestack-monitor#6]
#### 이슈 타입

~~~
 * 기능 개선 요청
 ~~~

#### 컴포넌트 이름

~~~
monitoring, memballoon
~~~

#### ABLESTACK 버전

~~~
ABLESTACK Bronto
~~~

#### 구성

~~~
가상머신 모니터링 데이터 수집
~~~

#### OS / 환경

~~~
CentOS 8.3, Prometheus-2.26.0, libvirt_exporter
~~~

#### 이슈 내용

libvirt_exporter를 활용하여 가상머신의 메모리 사용량 정보를 가져오기 위한 가상머신 운영체제 (windows, linux) 별 memballoon 드라이버 설정이 필요합니다. 클라우드 스택에서 가상머신 define 할 때 memballoon 설정이 자동으로 적용될 수 있도록 mold에도 추가 반영이 필요합니다.

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by kt-cheon** [comment]
Memballoon 드라이버 설정은 Bronto 버전부터 적용되어 서비스 됩니다.
