### ISSUE TITLE
multi-hypervisor 모니터링 지원을 위한 방안

### ISSUE THREAD

**Issue by qoxown12** [ablecloud-team/ablestack-monitor#7]
#### 이슈 타입

~~~
 * 새 기능 아이디어
 ~~~

#### 컴포넌트 이름

~~~
multi-hypervisor monitoring
~~~

#### ABLESTACK 버전

~~~
ABLESTACK Bronto
~~~

#### 구성

~~~
vmware, xen Monitoring 
~~~

#### OS / 환경

~~~
CentOS 8.3, wmware, xen, grafana, node_exporter, windows_exporter
~~~

#### 이슈 내용

libvirt_exporter를 활용한 가상머신 모니터링 정보를 수집할 경우 하이퍼 hypervisor 가 kvm인 가상머신만 모니터링 정보를 수집할 수 있는 문제가 있습니다. 다양한 멀티 하이퍼바이저 환경에서 통합적으로 모니터링할 수 있는 방안이 필요합니다.

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by kt-cheon** [comment]
Bronto 버전에서는 멀티 하이퍼바이저를 지원하지 않습니다. KVM 기반의 ABLESTACK에서만 Wall 서비스를 제공합니다.
