### ISSUE TITLE
ABLESTACK Monitor의 확장성과 가용성 문제를 해결하기 위한 방안

### ISSUE THREAD

**Issue by stardom3645** [ablecloud-team/ablestack-monitor#8]
#### 이슈 타입

 * 새 기능 아이디어

#### 컴포넌트 이름

~~~
HA
~~~

#### ABLESTACK 버전

~~~
BRONTO(2.0.0)
~~~

#### 구성

~~~
ABLESTACK Monitor
~~~

#### OS / 환경

~~~
Centos8
~~~

#### 이슈 내용

기본적으로 프로메테우스는 클러스터링 구조를 지원하지 않아 확장성과 가용성 문제가 발생할 수 있어 이를 해결하기 위한 방안이 필요하며 고려해야할 점은 아래와 같습니다.

확장성:
- 오래된 데이터를 효율적으로 오래 저장 가능하도록.
- 로컬디스크가 아닌 외부 스토리지에 저장 가능하록.

고가용성:
- 고가용성 설계로 인한 중복된 메트릭 값 제거.

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~
하나의 타겟(모니터링 대상)에 여러 개의 프로메테우스 서버를 구성하여 하나의 프로메테우스 서버가 다운이 되어도 메트릭 수집이 중단되지 않도록 개발
~~~

#### 실제 결과

~~~

~~~

**Comment by stardom3645** [comment]
타노스(https://thanos.io)라는 오픈소스를 활용하여 기존 프로메테우스가 가진 확장성과 가용성 부분의 단점을 보완할 수 있을 것 같습니다.

**Comment by stardom3645** [comment]
![prometheus-with-Thanos-arch-mini](https://user-images.githubusercontent.com/34114265/117919904-db0c1d00-b328-11eb-92cf-432dfa6ede4b.png)
*하나의 타겟에 2개 이상의 프로메테우스 서버 구성 아키텍처 구성 (축소)*

![prometheus-with-Thanos-arch-large png](https://user-images.githubusercontent.com/34114265/117919915-e3fcee80-b328-11eb-83ba-e2ac17211430.png)
*하나의 타겟에 2개 이상의 프로메테우스 서버 구성 아키텍처 구성 (확장)*

**Comment by kt-cheon** [comment]
### Monitoring VM의 확장성 및 가용성
Monitoring VM (prometheus가 설치된 VM)은 기존 CCVM과 같이 PCS resource를 생성하여 관리하는 방법도 있습니다.
PCS를 이용하는 방법은 Thanos가 제공하는 외부 스토리지(ceph, s3)를 사용하는 방법도 제공합니다.

**Comment by kt-cheon** [comment]
Bronto 버전에서는 기존 CCVM에서 모니터링 서비스를 지원합니다.(pcs 기반)
